version: '3.1'

services:
  mongo:
    image: mongo:5.0
    volumes:
      - ./mongo-volume:/data/db
    restart: always

  bot:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
