version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          region: AWS_REGION
          registry_id: ${AWS_ACCOUNT_URL}
          repo: ${ECR_REPOSITORY_NAME}
          tag: ${ENVIRONMENT}
      - aws-ecs/deploy_service_update:
          cluster: ${AWS_ECS_CLUSTER}
          container_image_name_updates: container=bot,image-and-tag=${AWS_ACCOUNT_URL}/${ECR_REPOSITORY_NAME}:${ENVIRONMENT}
          family: ${AWS_ECS_SERVICE}
          requires:
            - aws-ecr/build-and-push-image
