version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  build_and_push_image:
    docker:
      - image: cimg/aws:2024.03.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: ${ECR_REPOSITORY_NAME}
          region: AWS_REGION
          tag: prod_cci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push_image
